# AWS Configuration
aws:
  aws_region: "us-east-1"
  aws_access_key_id: "YOUR_ACCESS_KEY_ID"
  aws_secret_access_key: "YOUR_SECRET_ACCESS_KEY"
  aws_session_token : "YOUR_SESSION_TOKEN"
  s3_bucket_name: "shubham-pyspark-buck"
  folder_name : "Regiments"
  input_data_folder : "input_data"
  output_data_folder: "output_data"
